### ISSUE TITLE
DevTools on Mac?

### ISSUE THREAD

**Issue by iliyang** [typora/theme.typora.io#104]
Typora doesn't seem to support DevTools on Mac. This is unfortunate because exploring the UI with the DevTools makes it so much easier to see which CSS classes correspond to which UI elements. Are there any plans to enable DevTools on Mac?

**Comment by abnerlee** [comment]
Yes -> http://support.typora.io/Add-Custom-CSS/#debug-css

**Comment by iliyang** [comment]
Perfect, thank you!
