### ISSUE TITLE
Suggestion: Innate column handling

### ISSUE THREAD

**Issue by TEParsons** [typora/theme.typora.io#172]
A user has contacted me with a bug about the Torillic theme to do with columns, as I style them in using CSS. It made me think, CSS columns are a bit lacking, so it would be pretty neat if Typora had some innate functionality for displaying content in multiple columns, possibly in the View menu? I wager you'd do a better job of it than CSS!

Feel free to delete if the Issues feed isn't the best place for this! Now that Discord Discussions exists I imagine you might want to move suggestions like this over to there.

**Comment by abnerlee** [comment]
For a writing app, it is a good idea, but Typora is based on Markdown, which does not have syntax for "columns"... 

So maybe not for Typora, but for future writing apps
