### ISSUE TITLE
ERROR: [Mermaid] Parse error

### ISSUE THREAD

**Issue by DraftPaper** [typora/theme.typora.io#183]
问题：为什么出现"parent"会导致语法解析错误

```mermaid
graph TD
	a_parent(start) --> a_child[test]
```
![image](https://user-images.githubusercontent.com/50624956/105940092-7c7ea400-6095-11eb-8610-6dd280014184.png)

报错版本：0.9.98
正常版本：0.9.78

**Comment by abnerlee** [comment]
可以在 https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic3RhdGVEaWFncmFtLXYyXG4gICAgWypdIC0tPiBGaXJzdFxuXG4gICAgc3RhdGUgRmlyc3Qge1xuICAgICAgICBbKl0gLS0-IFNlY29uZFxuXG4gICAgICAgIHN0YXRlIFNlY29uZCB7XG4gICAgICAgICAgICBbKl0gLS0-IHNlY29uZFxuICAgICAgICAgICAgc2Vjb25kIC0tPiBUaGlyZFxuXG4gICAgICAgICAgICBzdGF0ZSBUaGlyZCB7XG4gICAgICAgICAgICAgICAgWypdIC0tPiB0aGlyZFxuICAgICAgICAgICAgICAgIHRoaXJkIC0tPiBbKl1cbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgIH0iLCJtZXJtYWlkIjp7InNlY3VyaXR5TGV2ZWwiOiJsb29zZSIsInRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ 上面测试


具体请参考 mermaid 的语法规则
