### ISSUE TITLE
mermaid loopText is not visible in dark theme

### ISSUE THREAD

**Issue by alfred-sa** [typora/theme.typora.io#199]
To correct, add this in night/mermaid.dark.css : 

[lang='mermaid'] .label {
  color: #333;

before : 
![2021-03-18-171804_808x254_scrot](https://user-images.githubusercontent.com/2234501/111659945-ea318b80-880d-11eb-9ef4-288ef355b994.png)

after : 
![2021-03-18-171730_775x249_scrot](https://user-images.githubusercontent.com/2234501/111659963-eef63f80-880d-11eb-9ba0-2a72813ff6cd.png)

**Comment by abnerlee** [comment]
fixed
