### ISSUE TITLE
How to submit a collection of themes with different color palette?

### ISSUE THREAD

**Issue by imageslr** [typora/theme.typora.io#220]
Hi all, I have made a collection of typora themes, corresponding to [bear](https://bear.app) themes.

The difference between these themes is only color palette. How can I publish them on the gallery? Can I just add a single post for them?

Homepage: https://github.com/imageslr/typora-theme-bear

Preview: 

![image](https://user-images.githubusercontent.com/17822028/124057235-a92a5380-da59-11eb-8b2f-d5bee4f7d712.png)

**Comment by abnerlee** [comment]
> The difference between these themes is only color palette. How can I publish them on the gallery? Can I just add a single post for them?

Yes, you can just submit one post with all those contants.
