### ISSUE TITLE
不支持中国支付宝

### ISSUE THREAD

**Issue by bode135** [typora/theme.typora.io#246]
> Don't support China Paypal.  

本来想买的, 研究了半天发现不支持中国的支付方式...  
得美区的palpay..
还直接禁用beta版...
![image](https://user-images.githubusercontent.com/40768803/143776697-2b2a9b1c-3f8d-4e68-af22-8cda297ebabd.png)

只能转`marktext`了.  
可惜.

**Comment by AntonVanke** [comment]
可以使用支付宝呀
![image](https://user-images.githubusercontent.com/47097086/143823215-f3bbc6bc-212d-4381-8d6b-af357140aec2.png)

---

查看这个页面
https://store.typora.io/#faq

**Comment by bode135** [comment]
> 可以使用支付宝呀 ![image](https://user-images.githubusercontent.com/47097086/143823215-f3bbc6bc-212d-4381-8d6b-af357140aec2.png)
> 
> 查看这个页面 https://store.typora.io/#faq

啊哈, 可能是我用的vpn就没看到~
下单了~~

**Comment by abnerlee** [comment]
PS： beta 版过期前需要升级到更新的 beta 版
