### ISSUE TITLE
Css file cannot be imported.

### ISSUE THREAD

**Issue by Haobin-Lee** [typora/theme.typora.io#269]
I downloaded the css file on the official website and copied it to the themes folder, but the theme cannot be used after restarting typora.Could you please tell me the solution to this problem？

**Comment by Cz1544252489** [comment]
Have you ever chosen the theme you download? And you should see this after you copied them to right place.
![Snipaste- Typora _2023-10-08_23-41-36](https://github.com/typora/theme.typora.io/assets/64407693/96ec38aa-c738-49b7-a9db-2058bdb2eb8b)
