### ISSUE TITLE
Some errors in exporting pdf files

### ISSUE THREAD

**Issue by KicyKnoty** [typora/theme.typora.io#289]
look another one

**Comment by KicyKnoty** [comment]
I made a Typora theme, but the title style was misaligned when I exported the pdf file. I checked and found that it was because I used relative position, and found in the test that the styles using relative position would be misaligned when exporting pdf files. Is it me or is it Typora? Is there a solution?

**Comment by abnerlee** [comment]
Are you using macOS version? Could you provide sample CSS and md file

**Comment by KicyKnoty** [comment]
> Are you using macOS version? Could you provide sample CSS and md file

Not MacOS, I try it at Windows11.
This is my file <https://github.com/KicyKnoty/MuXieLi>
