### ISSUE TITLE
Academic theme checkbox is a square root

### ISSUE THREAD

**Issue by madebyollin** [typora/theme.typora.io#29]
The lovely new Academic theme uses `U+221A` (SQUARE ROOT) for both checked and unchecked task list boxes.  I would suggest using `U+2610` (BALLOT BOX) and `U+2611` (BALLOT BOX WITH CHECK) as they seem, visually and semantically, a better fit with the professionalism of the rest of the theme.  

Here's what a task list in Academic looks like using the ballot box codepoints:

<img width="254" alt="screen shot 2018-02-17 at 7 14 18 pm" src="https://user-images.githubusercontent.com/8733615/36347835-cffb6538-1416-11e8-870d-e406681b966b.png">

**Comment by abnerlee** [comment]
Fixed
