### ISSUE TITLE
How can I submit my theme at "https://theme.typoraio.cn"?

### ISSUE THREAD

**Issue by KicyKnoty** [typora/theme.typora.io#291]
I tried to upload my theme according to the method provided by the official, but all my uploads failed. I would like to know if there is a problem with my uploading method or my file does not comply with the regulations? What is the solution or the right way to upload it?

**Comment by abnerlee** [comment]
Which theme / PR are you referring to? Once PR accepted, both https://theme.typoraio.cn and https://theme.typora.io will be updated.

**Comment by KicyKnoty** [comment]
This is my project, Every time I upload my project, it gets rejected. So I just upload it at my repository. If you can I want you help me to upload it.<https://github.com/KicyKnoty/MuXieLi>

> Which theme / PR are you referring to? Once PR accepted, both https://theme.typoraio.cn and https://theme.typora.io will be updated.

**Comment by YoukinoRen** [comment]
can i get your typora theme "MuXieLi", i really love it, the page was losing on github.

**Comment by KicyKnoty** [comment]
> can i get your typora theme "MuXieLi", i really love it, the page was losing on github.

Because I think there are a lot of problems with this theme, I chose to remove them from the shelves. I also found that there are quite a lot of people who like this theme, so I will upload it again. But I need time to optimize it, because I have other things to deal with, so I can only improve it in my spare time. I think it will take about one to two months. If you want to use it now and don't mind his imperfection, you can provide me with a contact information and I will send you the document separately.Maybe send your email to me.

**Comment by YoukinoRen** [comment]
Thank you for your reply, I can't wait to have a try , if possible you can send it to miziharen@gmail

**Comment by Regardles** [comment]
> I tried to upload my theme according to the method provided by the official, but all my uploads failed. I would like to know if there is a problem with my uploading method or my file does not comply with the regulations? What is the solution or the right way to upload it?

作者您好，我也很喜欢这款风格，如果可以的话我也想。
如果可以的话这是我的邮箱 j1041241756@outlook.com
