### ISSUE TITLE
Clicking Download Link for Scribble Theme Results in 404 Error

### ISSUE THREAD

**Issue by ahuber1** [typora/theme.typora.io#37]
I was trying to add the Scribble theme to my installation of Typora by 

1. Going to the [Typora Theme Gallery](http://theme.typora.io/), 
2. Going to the [page for the Scribble theme](http://theme.typora.io/theme/Scribble/)
3. Clicking the "Download" button.

Clicking the "Download" button, however, results in a 404 Error. The URL that I am taken to after clicking the "Download" button is

> https://github.com/ujwaljain/typora-theme-gallery/blob/gh-pages/media/theme/scribble/scribble.zip

**Comment by abnerlee** [comment]
Fixed link

**Comment by ahuber1** [comment]
Thank you very much :-)
