### ISSUE TITLE
Typora to Zhihu

### ISSUE THREAD

**Issue by liliaoyuan** [typora/theme.typora.io#376]
Is there a theme that perfectly match the zhihu sytle?
It is so annoy everytime I have to modify the format import local typora markdown
like subhead, list and  newline

**Comment by caolib** [comment]
主题不会改变语法，只是样式变化

**Comment by liliaoyuan** [comment]
> 主题不会改变语法，只是样式变化

感谢，我这边最后用了hexo做了代替方案
