### ISSUE TITLE
What is the theme on the main page?

### ISSUE THREAD

**Issue by DrJimFan** [typora/theme.typora.io#39]
I wonder what's this theme displayed as the first item on Typora.io webpage? I looked at all the themes in the gallery but can't find it. I'd love to use this theme in my daily writing. 

![theme](https://typora.io/img/theme-prev/Snip20141101_4.png)

**Comment by abnerlee** [comment]
Whitey

It is a built-in theme for Typora

**Comment by DrJimFan** [comment]
I did check `whitey` before I posted the issue. Now I know why I thought `whitey` was different. Here's what I see on my Mac (Sierra). The font characters seem more "spread out" and "thinned", unlike the round and smooth feeling of the screenshot on your website. Is that caused by some kind of anti-aliasing/font smoothing setting? How can I make it render better?

<img width="500" alt="image" src="https://user-images.githubusercontent.com/3018029/41084022-ca988540-69e7-11e8-9525-ee75fac14dc0.png">
