### ISSUE TITLE
Alignment of mathematical formula with Academic style

### ISSUE THREAD

**Issue by On1gub** [typora/theme.typora.io#46]
The Interline formula is aligned centrally as shown in following picture.

![image](https://user-images.githubusercontent.com/43373866/46963525-79379800-d0d8-11e8-81e9-8fe13253b878.png)

However, he Interline formula is aligned left on my computer running Windows 10.

**Comment by abnerlee** [comment]
`$math$` is inline math,

```
$$
math
$$
```
is display block which are centered aligned.
