### ISSUE TITLE
Small Problems I found when creating a Theme

### ISSUE THREAD

**Issue by CrazyPython** [typora/theme.typora.io#6]
- Typora requires more than one restart to recognize new themes
   - To reproduce, duplicate a theme (say gothic) and change anything. Restart typora and select a theme different from the duplicated one (say github) and select the new theme. The theme won't change.
   - I had to restart Typora several times for the new themes to work
- A "reload themes" button would be a good addition to the preferences pane
- "Custom Themes" links to `typora.com` instead of `typora.io`

**Comment by mbedded** [comment]
Hello CrazyPython,
i saw your issue by accident (i just discovered Typora a few days ago and i am exploring their website right now). I think your should check your fist issues listed above ("restart Typora till it recognizes the new themes" and "reload button").

Issues belonging to the program itself should be posted in the according repository: https://github.com/typora/typora-issues/issues
It seems that the first two bullet-points are targeting the application. Maybe they have fixed the issue in the meantime.

**Comment by abnerlee** [comment]
Custom css has a naming rule, The file name should not include capitalised characters or whitespace, for example: my-typora-theme is a valid file name. (source: http://theme.typora.io/doc/Write-Custom-Theme/) So please make sure you renamed the css file after duplicate it.

If it still happens, please fire an issue on https://github.com/typora/typora-issues/issues
