### ISSUE TITLE
Typora not working on Linuxmint 19.2 Tina

### ISSUE THREAD

**Issue by tyway9** [typora/theme.typora.io#82]
I had been using Typora on Linuxmint 19.2 (beta) without any issue. However after upgrading from 0.9.72 to 0.9.73 on 3rd of August Typora fails to open. Now I have Linuxmint 19.2 (tina) and still Typora fails to open.

If there is any work around too will be glad to know.
Typora is an amazing piece of software and would love to see it on every linux machine I work on. Kudos to you guys for the outstanding work too!

**Comment by abnerlee** [comment]
https://github.com/typora/typora-issues/issues/2694
